UX improve
BGmi/BGmi-frontend pull request #129
Opened 2021-04-19 19:52 UTC by StoneMoe

1. 对UI和交互进行了微调
2. proxy支持通过环境变量获取

2021-04-19 19:58 UTC, Trim21 commented on src/pages/Bangumi.vue
> +      bangumi: [],
重新格式化一下代码？

2021-04-19 20:00 UTC, StoneMoe commented on src/pages/Bangumi.vue
> +      bangumi: [],
你比较偏向于用什么工具和方法来格式化？
或者我应该把代码风格类的change全部revert？

2021-04-19 20:25 UTC, Trim21 commented on src/pages/Bangumi.vue
> +      bangumi: [],
用prettier格式化一下吧

2021-04-20 04:26 UTC, StoneMoe commented on src/pages/Bangumi.vue
> +      bangumi: [],
.....这我要解决一堆conflict

2021-04-20 04:54 UTC, StoneMoe commented on src/pages/Bangumi.vue
> +      bangumi: [],
好了，你看一下

2021-04-20 04:55 UTC, StoneMoe commented
Rebase到了最新commit，并用指定工具跑了格式化

2021-04-20 07:23 UTC, Trim21 commented on src/components/Navigation.vue
> +    <md-dialog ref="dialog1" md-content="">
咋还是有这种样式上的更改…
为啥package-lock.json也被更新了…
你npm ci然后再格式化一下看看

2021-04-20 08:24 UTC, Trim21 commented
之前eslint的设置有点问题，再跑一下（

2021-04-20 12:52 UTC, StoneMoe commented
Done.

2021-04-21 04:57 UTC, StoneMoe commented
是格式还有问题吗？能提供一下您期望的格式化步骤吗？

2021-04-21 05:45 UTC, Trim21 commented
直接npm run prettier就好了…
（昨天是我发现有个commit忘了推了，抱歉

2021-04-21 05:47 UTC, StoneMoe commented
> 直接npm run prettier就好了…
> （昨天是我发现有个commit忘了推了，抱歉
> 
> 这个项目之前也没有其他人提过vue部分的PR，所以一直写的比较随性…

好的，那现在还有什么需要修改的地方吗？

2021-04-21 05:52 UTC, Trim21 commented
没有了，等晚上我测试一下

2021-04-27 12:01 UTC, StoneMoe commented
Any news?

2021-04-27 12:19 UTC, Trim21 commented
最近在忙别的（

2021-04-28 09:36 UTC, Trim21 requested changes

2021-04-28 09:36 UTC, Trim21 commented on src/pages/Bangumi.vue
> +                Object.keys(bg.player).reverse()[0] != bg.episode
```suggestion
                Object.keys(bg.player).reverse()[0] !== bg.episode
```

2021-04-28 10:08 UTC, merged