Refactor project
BGmi/BGmi-frontend pull request #219
Opened 2023-03-29 03:09 UTC by kahosan

2023-03-29 03:11 UTC, trim21 commented on pages/index.tsx
> +  const downloadStatus = episode > 0 && Object.keys(player).at(-1) !== episode.toString() ? '正在下载' : '';
这个不要显示`正在下载`吧，容易让用户误解

2023-03-29 03:13 UTC, kahosan commented on pages/index.tsx
> +  const downloadStatus = episode > 0 && Object.keys(player).at(-1) !== episode.toString() ? '正在下载' : '';
我按照原来的模式改的，直接删掉嘛？

2023-03-29 03:17 UTC, trim21 commented on pages/index.tsx
> +  const downloadStatus = episode > 0 && Object.keys(player).at(-1) !== episode.toString() ? '正在下载' : '';
原来我记得是直接空白什么都不显示的

2023-03-30 05:57 UTC, trim21 commented
husky和prettier怎么给删了

2023-03-30 06:00 UTC, kahosan commented
> husky和prettier怎么给删了

prettier 确实用不到
husky 我没用过

可以配一下 husky，你有什么要求嘛

2023-03-30 06:01 UTC, trim21 commented
需求是加上prettier（）

2023-03-30 06:02 UTC, trim21 commented
还有动力虐。

2023-03-30 06:46 UTC, kahosan commented
配好了，看看

2023-03-30 14:26 UTC, trim21 commented on .husky/.gitignore
这文件怎么给删了

2023-03-30 14:27 UTC, trim21 commented on .prettierrc
不要改文件名

2023-03-30 14:27 UTC, trim21 commented on README.md
> +git clone github.com/kahosan/BGmi-frontend.git
写错地址了

2023-03-30 14:28 UTC, trim21 commented on README.md
> +如果你想使用网站的子域名, 按照如下配置
是子路径不是子域名

2023-03-31 00:34 UTC, kahosan commented on .husky/.gitignore
<img width="494" alt="image" src="https://user-images.githubusercontent.com/33192552/228993389-6aeb7908-094a-4679-880f-84cb301d1a61.png">

husky install 的时候自带了

2023-03-31 00:43 UTC, trim21 commented on .husky/.gitignore
ok

2023-03-31 00:43 UTC, trim21 commented
解决一下冲突

2023-03-31 11:12 UTC, trim21 commented on README.md
> +**部署前请先将 bgmi 的 `serve_static_files` 设置为 `true` 并执行 `bgmi cal --download-cover`**
删了这一行吧，不需要加这个

2023-03-31 11:13 UTC, trim21 commented on package.json
> +  "version": "2.0.0",
这里不用改... 我会直接发成v2的

2023-03-31 11:14 UTC, trim21 commented on package.json
> +    "front_static",
应该输出到`dist`文件夹，这样我就不用改python代码了

2023-03-31 11:17 UTC, trim21 requested changes

2023-03-31 11:17 UTC, trim21 commented on package.json
> +    "front_static",
我之前说的 `front_static` 只是用在nginx里面的，不是说希望build之后输出到 front_static 文件夹

2023-03-31 11:37 UTC, merged